experiment_name: "louvain_reddit_D"
dataset: "reddit"
type: "baseline"
num_runs: 5
data_path: "data/processed/reddit/snapshots/reddit_snapshots_D.parquet"
graph_path: "data/processed/reddit/graphs/reddit_graph_D.gexf"
features:
  load_save: true
  X_path: "features/reddit/node/sequences_D.pt"
  t_path: "features/reddit/node/labels_D.pt"
  minmax_scaler: false
  
clustering: "louvain"
hyperparams:
  lr: 0.01
  hidden_dim: 16

# Test Accuracy: 0.8111 ± 0.0026
#Test Accuracy: 0.8103 ± 0.0070